apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: demo-quarkus
  name: demo-quarkus
spec:
  replicas: {{ .Values.application.replicas | default 1 }}
  selector:
    matchLabels:
      component: demo-quarkus
  template:
    metadata:
      labels:
        component: demo-quarkus
    spec:
      # pod spec, we want a single container in our pods
      containers:
        - name: demo-quarkus
          image:  {{ .Values.application.image.registry }}/{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}
          imagePullPolicy: Always
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgresql:{{ .Values.postgres.service.port }}/demo
            - name: QUARKUS_DATASOURCE_USERNAME
              value: demo
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: demo
            - name: quarkus.opentelemetry.enabled
              value: "true"
            - name: quarkus.opentelemetry.tracer.exporter.otlp.endpoint
              value: http://otel-agent:4317
            - name: quarkus.application.name
              value: demo-quarkus
          # live & ready probes, using our healthcheck endpoints
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: {{ .Values.application.livenessProbe.url }}
              port: {{ .Values.application.pod.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - containerPort: {{ .Values.application.pod.port }}
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: {{ .Values.application.readinessProbe.url }}
              port: {{ .Values.application.pod.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
      # we can define init containers, single run jobs that run before our main container does
      # we use them to init database and check that its ready
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - >-
              psql -tc "SELECT 1 FROM pg_database WHERE datname =
              'demo'" | grep -q 1 | psql -c "CREATE USER
              demo WITH ENCRYPTED PASSWORD 'demo';" -c
              "CREATE DATABASE demo;" -c "GRANT ALL PRIVILEGES
              ON DATABASE demo TO demo;"
          env:
            - name: PGHOST
              value: postgresql
            - name: PGPORT
              value: '{{ .Values.postgres.service.port }}'
            - name: PGDATABASE
              value: null
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: DISABLE_WELCOME_MESSAGE
              value: 'true'
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}
          name: create-db
        - command:
            - /bin/bash
            - '-c'
            - until pg_isready; do echo waiting for database; sleep 2; done;
          env:
            - name: PGHOST
              value: postgresql
            - name: PGPORT
              value: '{{ .Values.postgres.service.port }}'
            - name: PGDATABASE
              value: demo
            - name: PGUSER
              value: demo
            - name: PGPASSWORD
              value: demo
            - name: DISABLE_WELCOME_MESSAGE
              value: 'true'
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}
          name: check-db

---

apiVersion: v1
kind: Service
metadata:
  labels:
    component: demo-quarkus
  name: demo-quarkus
spec:
  ports:
  - name: demo-quarkus-port
    port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.pod.port }}
  selector:
    component: demo-quarkus
