kind: Service
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: tcp-postgresql
  selector:
    app: postgresql
  type: LoadBalancer #ClusterIP
status:
   loadBalancer: {}
